#!/usr/bin/env bash
# =============================================================================
# 360 SaaS - Environment File Generator
# Interactively creates backend/.env and frontend/.env from user input.
# Usage:
#   bash scripts/setup-env.sh              # full setup
#   bash scripts/setup-env.sh --backend-only
#   bash scripts/setup-env.sh --frontend-only
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

log()  { echo -e "${BLUE}[ENV]${NC}   $*"; }
ok()   { echo -e "${GREEN}[ENV]${NC}   $*"; }
warn() { echo -e "${YELLOW}[ENV]${NC}   $*"; }

SETUP_BACKEND=true
SETUP_FRONTEND=true

while [[ $# -gt 0 ]]; do
  case $1 in
    --backend-only)  SETUP_FRONTEND=false; shift ;;
    --frontend-only) SETUP_BACKEND=false;  shift ;;
    *) shift ;;
  esac
done

# Helper: prompt with default
prompt() {
  local VAR_NAME="$1"
  local PROMPT_TEXT="$2"
  local DEFAULT="${3:-}"
  local SECRET="${4:-false}"
  local INPUT

  if [[ "$SECRET" == "true" ]]; then
    read -rsp "  ${PROMPT_TEXT} [default: ${DEFAULT}]: " INPUT
    echo
  else
    read -rp "  ${PROMPT_TEXT} [default: ${DEFAULT}]: " INPUT
  fi

  INPUT="${INPUT:-$DEFAULT}"
  printf -v "$VAR_NAME" '%s' "$INPUT"
}

# Helper: generate a random 64-char hex secret
gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 64 | head -1
  fi
}

# ===========================================================================
# Backend .env
# ===========================================================================
if [[ "$SETUP_BACKEND" == "true" ]]; then
  BACKEND_ENV="${ROOT_DIR}/backend/.env"

  if [[ -f "$BACKEND_ENV" ]]; then
    warn "backend/.env already exists."
    read -rp "  Overwrite? [y/N]: " OVERWRITE
    [[ "${OVERWRITE,,}" == "y" ]] || { log "Skipping backend .env."; SETUP_BACKEND=false; }
  fi

  if [[ "$SETUP_BACKEND" == "true" ]]; then
    echo -e "\n${BOLD}--- Backend Environment Setup ---${NC}"

    prompt DB_HOST     "MySQL host"     "localhost"
    prompt DB_PORT     "MySQL port"     "3306"
    prompt DB_NAME     "Database name"  "saas360"
    prompt DB_USER     "MySQL user"     "saas360user"
    prompt DB_PASSWORD "MySQL password" "" "true"

    AUTO_SECRET=$(gen_secret)
    prompt JWT_SECRET "JWT secret (leave blank to auto-generate)" "$AUTO_SECRET" "true"
    [[ -n "$JWT_SECRET" ]] || JWT_SECRET="$AUTO_SECRET"

    prompt PORT "API server port" "3000"
    prompt NODE_ENV "Node environment" "production"

    cat > "$BACKEND_ENV" <<EOF
# Generated by scripts/setup-env.sh on $(date)

# MySQL Database
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=${DB_NAME}

# JWT
JWT_SECRET=${JWT_SECRET}

# Server
PORT=${PORT}
NODE_ENV=${NODE_ENV}
EOF

    chmod 600 "$BACKEND_ENV"
    ok "backend/.env created at ${BACKEND_ENV}"
  fi
fi

# ===========================================================================
# Frontend .env
# ===========================================================================
if [[ "$SETUP_FRONTEND" == "true" ]]; then
  FRONTEND_ENV="${ROOT_DIR}/frontend/.env"

  if [[ -f "$FRONTEND_ENV" ]]; then
    warn "frontend/.env already exists."
    read -rp "  Overwrite? [y/N]: " OVERWRITE
    [[ "${OVERWRITE,,}" == "y" ]] || { log "Skipping frontend .env."; SETUP_FRONTEND=false; }
  fi

  if [[ "$SETUP_FRONTEND" == "true" ]]; then
    echo -e "\n${BOLD}--- Frontend Environment Setup ---${NC}"

    # Backend port for API URL (read from backend .env if available)
    BACKEND_PORT="3000"
    if [[ -f "${ROOT_DIR}/backend/.env" ]]; then
      # shellcheck source=/dev/null
      BACKEND_PORT=$(grep -E '^PORT=' "${ROOT_DIR}/backend/.env" | cut -d= -f2 || echo "3000")
    fi

    prompt VITE_API_URL "Backend API URL" "http://localhost:${BACKEND_PORT}"
    prompt VITE_TENANT_ID "Default Tenant ID (leave blank - set per user)" ""

    cat > "$FRONTEND_ENV" <<EOF
# Generated by scripts/setup-env.sh on $(date)

VITE_API_URL=${VITE_API_URL}
VITE_TENANT_ID=${VITE_TENANT_ID}
EOF

    ok "frontend/.env created at ${FRONTEND_ENV}"
  fi
fi

echo -e "\n${GREEN}Environment setup complete.${NC}\n"
echo "  Run 'bash deploy.sh' to deploy, or:"
echo "  Run 'bash scripts/setup-db.sh' to set up the database only."
