#!/usr/bin/env bash
# =============================================================================
# 360 SaaS - Service Startup Script (PM2)
# Starts/restarts backend API and frontend static server via PM2.
# Usage:
#   bash scripts/start.sh [production|staging|development]
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log()  { echo -e "${BLUE}[PM2]${NC}   $*"; }
ok()   { echo -e "${GREEN}[PM2]${NC}   $*"; }
warn() { echo -e "${YELLOW}[PM2]${NC}   $*"; }

DEPLOY_ENV="${1:-production}"

# Source backend .env for PORT
ENV_FILE="${ROOT_DIR}/backend/.env"
[[ -f "$ENV_FILE" ]] || { warn "backend/.env not found"; }
if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck source=/dev/null
  source "$ENV_FILE"
  set +a
fi

BACKEND_PORT="${PORT:-3000}"
FRONTEND_PORT="5000"
FRONTEND_DIST="${ROOT_DIR}/frontend/dist"

# ---------------------------------------------------------------------------
# Validate frontend build exists
# ---------------------------------------------------------------------------
if [[ ! -d "$FRONTEND_DIST" ]]; then
  warn "Frontend dist not found at ${FRONTEND_DIST}. Building now..."
  cd "${ROOT_DIR}/frontend"
  npm run build
  cd "$ROOT_DIR"
fi

# ---------------------------------------------------------------------------
# Generate PM2 ecosystem file
# ---------------------------------------------------------------------------
ECO_FILE="${ROOT_DIR}/ecosystem.config.js"
cat > "$ECO_FILE" <<ECOSYSTEM
// Auto-generated by scripts/start.sh
module.exports = {
  apps: [
    {
      name: '360saas-api',
      script: 'src/server.js',
      cwd: '${ROOT_DIR}/backend',
      instances: 1,
      exec_mode: 'fork',
      env_file: '${ROOT_DIR}/backend/.env',
      env: {
        NODE_ENV: '${DEPLOY_ENV}',
        PORT: ${BACKEND_PORT},
      },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 2000,
      error_file: '${ROOT_DIR}/logs/api-error.log',
      out_file: '${ROOT_DIR}/logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: '360saas-frontend',
      script: 'serve',
      args: '-s dist -l ${FRONTEND_PORT}',
      cwd: '${ROOT_DIR}/frontend',
      interpreter: 'none',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      error_file: '${ROOT_DIR}/logs/frontend-error.log',
      out_file: '${ROOT_DIR}/logs/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
};
ECOSYSTEM

ok "PM2 ecosystem config written to ${ECO_FILE}"

# ---------------------------------------------------------------------------
# Create log directory
# ---------------------------------------------------------------------------
mkdir -p "${ROOT_DIR}/logs"

# ---------------------------------------------------------------------------
# Start or reload with PM2
# ---------------------------------------------------------------------------
if pm2 list | grep -q '360saas-api'; then
  log "Reloading existing PM2 processes..."
  pm2 reload "$ECO_FILE" --update-env
  ok "Services reloaded."
else
  log "Starting services for the first time..."
  pm2 start "$ECO_FILE"
  ok "Services started."
fi

# Save PM2 process list for auto-restart on reboot
pm2 save

# Setup PM2 startup script (only if not already configured)
if ! pm2 startup 2>&1 | grep -q 'already'; then
  log "Configuring PM2 startup on system boot..."
  pm2 startup || warn "PM2 startup config requires sudo - run the displayed command manually."
fi

# ---------------------------------------------------------------------------
# Status summary
# ---------------------------------------------------------------------------
echo
pm2 list
echo
ok "Backend API  : http://localhost:${BACKEND_PORT}"
ok "Frontend     : http://localhost:${FRONTEND_PORT}"
ok "Logs dir     : ${ROOT_DIR}/logs/"
ok "Manage with  : pm2 list | pm2 logs | pm2 restart all | pm2 stop all"
